### ISSUE TITLE
Any chance to maven.compiler.target to 1.7?

### ISSUE THREAD

**Issue by hithwen** [vdmeer/asciitable#1]
I'm using this in a script I pass to people that do not have Java 8 installed

**Comment by vdmeer** [comment]
I need to look at the code base for v0.0.2 (the one that's on Maven Central), it might be possible. For v0.0.3 (current GitHub code) it will not work since J8 features are used all over the place (default methods in interfaces and the like).

Are you using v0.0.2 or are you building from current GitHub code?

**Comment by hithwen** [comment]
I'm using 0.0.2, thanks for looking into it

**Comment by vdmeer** [comment]
Someone has tried that before, have a look at this repo: https://github.com/dmitrygusev/asciitable

**Comment by vdmeer** [comment]
I have a J7 version compiled now, seems to work. Where do you want that going to?

**Comment by vdmeer** [comment]
Change of plans: I have just released asciitable v0.0.5, which is now a Java7 implementation. it contains a v1 (the old one) and a v2 (a new) table implementation. The release just went through sonatype, next update and it should be on maven central. You might need to check your code (packages changed), but beside that it should do the job and run in Java 7.

**Comment by hithwen** [comment]
Thank you very much, I won't have time to revisit until a few weeks from now, i'll let you know if I have any issues

**Comment by vdmeer** [comment]
Yes, please do. Open a new issue on v0.0.5 for any problems (it's java7 now). Thanks!

**Comment by vdmeer** [comment]
Just to let you know: v0.2.2 is now out (in a couple of hours also on Maven Central). All Java 7 with lots of additions for V2 table.
/sven

**Comment by hithwen** [comment]
Thanks!

Sent with MailTrack
https://mailtrack.io/install?source=signature&lang=en&referral=hithwen@gmail.com&idSignature=22
