### ISSUE TITLE
Respect new line breaks in cells

### ISSUE THREAD

**Issue by sebthom** [vdmeer/asciitable#2]
The following code:

```
    final V2_AsciiTable at = new V2_AsciiTable();
    at.addRule();
    at.addRow("request", "status", "causes");
    at.addRule();
    at.addRow("1", "invalid", "* size limit exceeded\n* invalid characters found");
    at.addRule();
    at.addRow("2", "valid", "* all requirements satisfied");
    at.addRule();
    final V2_AsciiTableRenderer rend = new V2_AsciiTableRenderer();
    rend.setTheme(V2_E_TableThemes.PLAIN_7BIT.get());
    rend.setWidth(new WidthFixedColumns().add(10).add(10).add(40));
    final RenderedTable rt = rend.render(at);
    System.out.println(rt);
```

results in:

```
+----------+----------+----------------------------------------+
| request  | status   | causes                                 |
+----------+----------+----------------------------------------+
| 1        | invalid  | * size limit exceeded
* invalid        |
|          |          | characters found                       |
+----------+----------+----------------------------------------+
| 2        | valid    | * all requirements satisfied           |
+----------+----------+----------------------------------------+
```

but should result in:

```
+----------+----------+----------------------------------------+
| request  | status   | causes                                 |
+----------+----------+----------------------------------------+
| 1        | invalid  | * size limit exceeded                  |
|          |          | * invalid characters found             |
+----------+----------+----------------------------------------+
| 2        | valid    | * all requirements satisfied           |
+----------+----------+----------------------------------------+
```

**Comment by vdmeer** [comment]
Yes, lists and paragraphs are not handled (yet) by the renderer. I have an idea how to do that, but didn't get time to try it out.

For paragraphs it should be easy, for lists it might be tricky if the line needs to be wrapped later, since the list introduces indentation.

I'll have that on the todo list now.
thanks
/sven

**Comment by vdmeer** [comment]
Fix for line break added, now in the dev branch. Your WidthLongestLine works nicely now. Also added the test of this issue to the examples in test test code, will add it to the main documentation later (for next release).

Thanks!
/sven

**Comment by vdmeer** [comment]
Nachtrag / After math

I have created a new repo for AsciiList with all sorts of lists initially supported. Those lists can wrap themselves against a given width (and have all sorts of other features, like nested lists and styles). I will add those lists to the AsciiTable in the next table's release, then once can use either manual lists (as in your example, which now works) or the new lists.

Thanks very much for your contribution!
/sven
