### ISSUE TITLE
Emails not displayed correctly

### ISSUE THREAD

**Issue by jpuerto** [vdmeer/asciitable#4]
Hi,

If I try to print an email in the content, the "at" character is translated to a new line. The problem seems to be in method

de.vandermeer.asciitable.commons.ArrayTransformations.WRAP_LINES(int, Object)

**Comment by vdmeer** [comment]
Yes, I am using "@@@@" as substitution string, and that collides with email addresses. I'll change that for next release and add tests for various other cases (like URLs) to avoid the problem in the future.

**Comment by jpuerto** [comment]
I think that you could use "\n" as new line character, this way it will not conflict with other chars as it has the new line meaning.

**Comment by vdmeer** [comment]
There was a reason for not using '\n', that got solved earlier by pre-processing content. I have changed the wrapping to use '\n' now and added tests for URIs. Will be in next release.
