### ISSUE TITLE
How to do span, content into list, etc in the example ?

### ISSUE THREAD

**Issue by albert-kam** [vdmeer/asciitable#6]
Would be nice to copy snippets of code along with the output in the main page examples !

I've tried looking at your test/ and also autocomplete from my ide on the table, row, renderer, etc, but cannot seem to find the way to do column spanning, content becoming a list, etc.

Thanks.

**Comment by andrea-rockt** [comment]
This should answer your question:

https://github.com/vdmeer/asciitable/blob/master/src/test/java/de/vandermeer/asciitable/v2/Test_CodeForDocs_V2.java

**Comment by albert-kam** [comment]
Thanks a lot my man !

**Comment by vdmeer** [comment]
Sorry for late reply, I did rewrite my baseline. The new AsciiTable is now published, and it comes with examples (src/test/.../examples) and a site detailing them: http://www.vandermeer.de/projects/skb/java/asciitable/

This should make it easier to use the table. 

Sorry for having neglected documentation...my bad!

/sven

**Comment by vdmeer** [comment]
I also have updated the skb-examples and added a binary package on bintray.com - https://bintray.com/vdmeer/generic/skb-examples/0.0.8

Simply download version 0.0.8 there, extract, 'cd bin', './init.sh', then depending on your system go to system-specific folder (sh-unix, cyg=cygwin, bat=dos/windows), there run asciitable-shell.sh.

/sven
