### ISSUE TITLE
Add configurable line separator

### ISSUE THREAD

**Issue by stuchl4n3k** [vdmeer/asciitable#8]
**Problem:**
- Tables generated on Linux cannot be displayed properly on MsWin (e.g. notepad).
- Line separator is hardcoded (e.g. `AsciiTable.render()`).

**Suggested solution:**
- Use [`System.lineSeparator()`](http://docs.oracle.com/javase/8/docs/api/java/lang/System.html#lineSeparator--) instead of hardcoded "\n" in table rendering.
- And/or allow configuration of the separator per table instance.

**Workaround:**
```java
String asciiTableRenderWithPlatformSeparator(AsciiTable table) {
        return new StrBuilder().appendWithSeparators(
            table.getRenderer().render(table.getRawContent(), table.getColNumber(), table.getContext()), System.lineSeparator()
        ).toString();
}
```

**Comment by vdmeer** [comment]
Yes, the line separator should be configurable. Good feature. Adding it to the table context alone means the renderer cannot control it, and line separator should be controllable by the renderer. I have added a configurable member to table context and renderer. See if that helps, new version in master and on Maven.

**Comment by stuchl4n3k** [comment]
Thanks!
